app.build.ui.mode=${build.ui.mode}
app.build.ui.ng.config=${build.ui.ng.config}
app.build.ui.spa.enabled=true
app.prefabs.lazyInit=true
build.ui.mode=react
build.ui.ng.config=--c=production
build.ui.node.args=--max-old-space-size=1024
