/*
 * LoanCorp Service Swagger Documentation
 * Swagger API documentation for loancorp
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.figmaapp.LoanCorpAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * LoanDoc
 */

public class LoanDoc {
  @JsonProperty("docName")
  private String docName = null;

  @JsonProperty("loan")
  private Loan loan = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("loanId")
  private Long loanId = null;

  @JsonProperty("docPath")
  private String docPath = null;

  public LoanDoc docName(String docName) {
    this.docName = docName;
    return this;
  }

   /**
   * Get docName
   * @return docName
  **/
  public String getDocName() {
    return docName;
  }

  public void setDocName(String docName) {
    this.docName = docName;
  }

  public LoanDoc loan(Loan loan) {
    this.loan = loan;
    return this;
  }

   /**
   * Get loan
   * @return loan
  **/
  public Loan getLoan() {
    return loan;
  }

  public void setLoan(Loan loan) {
    this.loan = loan;
  }

  public LoanDoc id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LoanDoc loanId(Long loanId) {
    this.loanId = loanId;
    return this;
  }

   /**
   * Get loanId
   * @return loanId
  **/
  public Long getLoanId() {
    return loanId;
  }

  public void setLoanId(Long loanId) {
    this.loanId = loanId;
  }

  public LoanDoc docPath(String docPath) {
    this.docPath = docPath;
    return this;
  }

   /**
   * Get docPath
   * @return docPath
  **/
  public String getDocPath() {
    return docPath;
  }

  public void setDocPath(String docPath) {
    this.docPath = docPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanDoc LoanDoc = (LoanDoc) o;
    return Objects.equals(this.docName, LoanDoc.docName) &&
        Objects.equals(this.loan, LoanDoc.loan) &&
        Objects.equals(this.id, LoanDoc.id) &&
        Objects.equals(this.loanId, LoanDoc.loanId) &&
        Objects.equals(this.docPath, LoanDoc.docPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docName, loan, id, loanId, docPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanDoc {\n");
    
    sb.append("    docName: ").append(toIndentedString(docName)).append("\n");
    sb.append("    loan: ").append(toIndentedString(loan)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
    sb.append("    docPath: ").append(toIndentedString(docPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
