/*
 * LoanCorp Service Swagger Documentation
 * Swagger API documentation for loancorp
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.figmaapp.LoanCorpAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
/**
 * LoanEmi
 */

public class LoanEmi {
  @JsonProperty("emiNumber")
  private Integer emiNumber = null;

  @JsonProperty("loan")
  private Loan loan = null;

  @JsonProperty("emiAmount")
  private Double emiAmount = null;

  @JsonProperty("dueDate")
  private LocalDate dueDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("loanId")
  private Long loanId = null;

  @JsonProperty("status")
  private String status = null;

  public LoanEmi emiNumber(Integer emiNumber) {
    this.emiNumber = emiNumber;
    return this;
  }

   /**
   * Get emiNumber
   * @return emiNumber
  **/
  public Integer getEmiNumber() {
    return emiNumber;
  }

  public void setEmiNumber(Integer emiNumber) {
    this.emiNumber = emiNumber;
  }

  public LoanEmi loan(Loan loan) {
    this.loan = loan;
    return this;
  }

   /**
   * Get loan
   * @return loan
  **/
  public Loan getLoan() {
    return loan;
  }

  public void setLoan(Loan loan) {
    this.loan = loan;
  }

  public LoanEmi emiAmount(Double emiAmount) {
    this.emiAmount = emiAmount;
    return this;
  }

   /**
   * Get emiAmount
   * @return emiAmount
  **/
  public Double getEmiAmount() {
    return emiAmount;
  }

  public void setEmiAmount(Double emiAmount) {
    this.emiAmount = emiAmount;
  }

  public LoanEmi dueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  public LocalDate getDueDate() {
    return dueDate;
  }

  public void setDueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
  }

  public LoanEmi id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LoanEmi loanId(Long loanId) {
    this.loanId = loanId;
    return this;
  }

   /**
   * Get loanId
   * @return loanId
  **/
  public Long getLoanId() {
    return loanId;
  }

  public void setLoanId(Long loanId) {
    this.loanId = loanId;
  }

  public LoanEmi status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanEmi LoanEmi = (LoanEmi) o;
    return Objects.equals(this.emiNumber, LoanEmi.emiNumber) &&
        Objects.equals(this.loan, LoanEmi.loan) &&
        Objects.equals(this.emiAmount, LoanEmi.emiAmount) &&
        Objects.equals(this.dueDate, LoanEmi.dueDate) &&
        Objects.equals(this.id, LoanEmi.id) &&
        Objects.equals(this.loanId, LoanEmi.loanId) &&
        Objects.equals(this.status, LoanEmi.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emiNumber, loan, emiAmount, dueDate, id, loanId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanEmi {\n");
    
    sb.append("    emiNumber: ").append(toIndentedString(emiNumber)).append("\n");
    sb.append("    loan: ").append(toIndentedString(loan)).append("\n");
    sb.append("    emiAmount: ").append(toIndentedString(emiAmount)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
