/*
 * LoanCorp Service Swagger Documentation
 * Swagger API documentation for loancorp
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.figmaapp.LoanCorpAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
/**
 * Loan
 */

public class Loan {
  @JsonProperty("autoPayEnabled")
  private Boolean autoPayEnabled = null;

  @JsonProperty("loanType")
  private LoanType loanType = null;

  @JsonProperty("endDate")
  private LocalDate endDate = null;

  @JsonProperty("totalAmount")
  private Double totalAmount = null;

  @JsonProperty("emiAmount")
  private Double emiAmount = null;

  @JsonProperty("balance")
  private Double balance = null;

  @JsonProperty("interest")
  private Float interest = null;

  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("loanStatusId")
  private Long loanStatusId = null;

  @JsonProperty("personEmail")
  private String personEmail = null;

  @JsonProperty("loanStatus")
  private LoanStatus loanStatus = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("applicationId")
  private String applicationId = null;

  @JsonProperty("principleAmount")
  private Double principleAmount = null;

  @JsonProperty("loanTypeId")
  private Long loanTypeId = null;

  @JsonProperty("tenure")
  private Integer tenure = null;

  @JsonProperty("startDate")
  private LocalDate startDate = null;

  public Loan autoPayEnabled(Boolean autoPayEnabled) {
    this.autoPayEnabled = autoPayEnabled;
    return this;
  }

   /**
   * Get autoPayEnabled
   * @return autoPayEnabled
  **/
  public Boolean isAutoPayEnabled() {
    return autoPayEnabled;
  }

  public void setAutoPayEnabled(Boolean autoPayEnabled) {
    this.autoPayEnabled = autoPayEnabled;
  }

  public Loan loanType(LoanType loanType) {
    this.loanType = loanType;
    return this;
  }

   /**
   * Get loanType
   * @return loanType
  **/
  public LoanType getLoanType() {
    return loanType;
  }

  public void setLoanType(LoanType loanType) {
    this.loanType = loanType;
  }

  public Loan endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public LocalDate getEndDate() {
    return endDate;
  }

  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }

  public Loan totalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Get totalAmount
   * @return totalAmount
  **/
  public Double getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }

  public Loan emiAmount(Double emiAmount) {
    this.emiAmount = emiAmount;
    return this;
  }

   /**
   * Get emiAmount
   * @return emiAmount
  **/
  public Double getEmiAmount() {
    return emiAmount;
  }

  public void setEmiAmount(Double emiAmount) {
    this.emiAmount = emiAmount;
  }

  public Loan balance(Double balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  public Double getBalance() {
    return balance;
  }

  public void setBalance(Double balance) {
    this.balance = balance;
  }

  public Loan interest(Float interest) {
    this.interest = interest;
    return this;
  }

   /**
   * Get interest
   * @return interest
  **/
  public Float getInterest() {
    return interest;
  }

  public void setInterest(Float interest) {
    this.interest = interest;
  }

  public Loan person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public Loan loanStatusId(Long loanStatusId) {
    this.loanStatusId = loanStatusId;
    return this;
  }

   /**
   * Get loanStatusId
   * @return loanStatusId
  **/
  public Long getLoanStatusId() {
    return loanStatusId;
  }

  public void setLoanStatusId(Long loanStatusId) {
    this.loanStatusId = loanStatusId;
  }

  public Loan personEmail(String personEmail) {
    this.personEmail = personEmail;
    return this;
  }

   /**
   * Get personEmail
   * @return personEmail
  **/
  public String getPersonEmail() {
    return personEmail;
  }

  public void setPersonEmail(String personEmail) {
    this.personEmail = personEmail;
  }

  public Loan loanStatus(LoanStatus loanStatus) {
    this.loanStatus = loanStatus;
    return this;
  }

   /**
   * Get loanStatus
   * @return loanStatus
  **/
  public LoanStatus getLoanStatus() {
    return loanStatus;
  }

  public void setLoanStatus(LoanStatus loanStatus) {
    this.loanStatus = loanStatus;
  }

  public Loan id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Loan applicationId(String applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  public String getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(String applicationId) {
    this.applicationId = applicationId;
  }

  public Loan principleAmount(Double principleAmount) {
    this.principleAmount = principleAmount;
    return this;
  }

   /**
   * Get principleAmount
   * @return principleAmount
  **/
  public Double getPrincipleAmount() {
    return principleAmount;
  }

  public void setPrincipleAmount(Double principleAmount) {
    this.principleAmount = principleAmount;
  }

  public Loan loanTypeId(Long loanTypeId) {
    this.loanTypeId = loanTypeId;
    return this;
  }

   /**
   * Get loanTypeId
   * @return loanTypeId
  **/
  public Long getLoanTypeId() {
    return loanTypeId;
  }

  public void setLoanTypeId(Long loanTypeId) {
    this.loanTypeId = loanTypeId;
  }

  public Loan tenure(Integer tenure) {
    this.tenure = tenure;
    return this;
  }

   /**
   * Get tenure
   * @return tenure
  **/
  public Integer getTenure() {
    return tenure;
  }

  public void setTenure(Integer tenure) {
    this.tenure = tenure;
  }

  public Loan startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public LocalDate getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Loan Loan = (Loan) o;
    return Objects.equals(this.autoPayEnabled, Loan.autoPayEnabled) &&
        Objects.equals(this.loanType, Loan.loanType) &&
        Objects.equals(this.endDate, Loan.endDate) &&
        Objects.equals(this.totalAmount, Loan.totalAmount) &&
        Objects.equals(this.emiAmount, Loan.emiAmount) &&
        Objects.equals(this.balance, Loan.balance) &&
        Objects.equals(this.interest, Loan.interest) &&
        Objects.equals(this.person, Loan.person) &&
        Objects.equals(this.loanStatusId, Loan.loanStatusId) &&
        Objects.equals(this.personEmail, Loan.personEmail) &&
        Objects.equals(this.loanStatus, Loan.loanStatus) &&
        Objects.equals(this.id, Loan.id) &&
        Objects.equals(this.applicationId, Loan.applicationId) &&
        Objects.equals(this.principleAmount, Loan.principleAmount) &&
        Objects.equals(this.loanTypeId, Loan.loanTypeId) &&
        Objects.equals(this.tenure, Loan.tenure) &&
        Objects.equals(this.startDate, Loan.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoPayEnabled, loanType, endDate, totalAmount, emiAmount, balance, interest, person, loanStatusId, personEmail, loanStatus, id, applicationId, principleAmount, loanTypeId, tenure, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Loan {\n");
    
    sb.append("    autoPayEnabled: ").append(toIndentedString(autoPayEnabled)).append("\n");
    sb.append("    loanType: ").append(toIndentedString(loanType)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    emiAmount: ").append(toIndentedString(emiAmount)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    interest: ").append(toIndentedString(interest)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    loanStatusId: ").append(toIndentedString(loanStatusId)).append("\n");
    sb.append("    personEmail: ").append(toIndentedString(personEmail)).append("\n");
    sb.append("    loanStatus: ").append(toIndentedString(loanStatus)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    principleAmount: ").append(toIndentedString(principleAmount)).append("\n");
    sb.append("    loanTypeId: ").append(toIndentedString(loanTypeId)).append("\n");
    sb.append("    tenure: ").append(toIndentedString(tenure)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
