/*
 * LoanCorp Service Swagger Documentation
 * Swagger API documentation for loancorp
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.figmaapp.LoanCorpAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * LoanDTO
 */

public class LoanDTO {
  @JsonProperty("autoPayEnabled")
  private Boolean autoPayEnabled = null;

  @JsonProperty("person")
  private PersonDTO person = null;

  @JsonProperty("principleAmount")
  private Double principleAmount = null;

  @JsonProperty("loanCategory")
  private String loanCategory = null;

  @JsonProperty("tenure")
  private Integer tenure = null;

  public LoanDTO autoPayEnabled(Boolean autoPayEnabled) {
    this.autoPayEnabled = autoPayEnabled;
    return this;
  }

   /**
   * Get autoPayEnabled
   * @return autoPayEnabled
  **/
  public Boolean isAutoPayEnabled() {
    return autoPayEnabled;
  }

  public void setAutoPayEnabled(Boolean autoPayEnabled) {
    this.autoPayEnabled = autoPayEnabled;
  }

  public LoanDTO person(PersonDTO person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public PersonDTO getPerson() {
    return person;
  }

  public void setPerson(PersonDTO person) {
    this.person = person;
  }

  public LoanDTO principleAmount(Double principleAmount) {
    this.principleAmount = principleAmount;
    return this;
  }

   /**
   * Get principleAmount
   * @return principleAmount
  **/
  public Double getPrincipleAmount() {
    return principleAmount;
  }

  public void setPrincipleAmount(Double principleAmount) {
    this.principleAmount = principleAmount;
  }

  public LoanDTO loanCategory(String loanCategory) {
    this.loanCategory = loanCategory;
    return this;
  }

   /**
   * Get loanCategory
   * @return loanCategory
  **/
  public String getLoanCategory() {
    return loanCategory;
  }

  public void setLoanCategory(String loanCategory) {
    this.loanCategory = loanCategory;
  }

  public LoanDTO tenure(Integer tenure) {
    this.tenure = tenure;
    return this;
  }

   /**
   * Get tenure
   * @return tenure
  **/
  public Integer getTenure() {
    return tenure;
  }

  public void setTenure(Integer tenure) {
    this.tenure = tenure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanDTO LoanDTO = (LoanDTO) o;
    return Objects.equals(this.autoPayEnabled, LoanDTO.autoPayEnabled) &&
        Objects.equals(this.person, LoanDTO.person) &&
        Objects.equals(this.principleAmount, LoanDTO.principleAmount) &&
        Objects.equals(this.loanCategory, LoanDTO.loanCategory) &&
        Objects.equals(this.tenure, LoanDTO.tenure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoPayEnabled, person, principleAmount, loanCategory, tenure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanDTO {\n");
    
    sb.append("    autoPayEnabled: ").append(toIndentedString(autoPayEnabled)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    principleAmount: ").append(toIndentedString(principleAmount)).append("\n");
    sb.append("    loanCategory: ").append(toIndentedString(loanCategory)).append("\n");
    sb.append("    tenure: ").append(toIndentedString(tenure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
