/*
 * LoanCorp Service Swagger Documentation
 * Swagger API documentation for loancorp
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.figmaapp.LoanCorpAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
/**
 * LoanSummaryDTO
 */

public class LoanSummaryDTO {
  @JsonProperty("totalInstallments")
  private Integer totalInstallments = null;

  @JsonProperty("totalPastInstallments")
  private Integer totalPastInstallments = null;

  @JsonProperty("totalPaidInstallments")
  private Integer totalPaidInstallments = null;

  @JsonProperty("percentagePayOff")
  private Double percentagePayOff = null;

  @JsonProperty("outstandingAmount")
  private Double outstandingAmount = null;

  @JsonProperty("installmentAmount")
  private Double installmentAmount = null;

  @JsonProperty("upcomingInstallmentDate")
  private LocalDate upcomingInstallmentDate = null;

  @JsonProperty("upcomingInstallmentLoanType")
  private String upcomingInstallmentLoanType = null;

  public LoanSummaryDTO totalInstallments(Integer totalInstallments) {
    this.totalInstallments = totalInstallments;
    return this;
  }

   /**
   * Get totalInstallments
   * @return totalInstallments
  **/
  public Integer getTotalInstallments() {
    return totalInstallments;
  }

  public void setTotalInstallments(Integer totalInstallments) {
    this.totalInstallments = totalInstallments;
  }

  public LoanSummaryDTO totalPastInstallments(Integer totalPastInstallments) {
    this.totalPastInstallments = totalPastInstallments;
    return this;
  }

   /**
   * Get totalPastInstallments
   * @return totalPastInstallments
  **/
  public Integer getTotalPastInstallments() {
    return totalPastInstallments;
  }

  public void setTotalPastInstallments(Integer totalPastInstallments) {
    this.totalPastInstallments = totalPastInstallments;
  }

  public LoanSummaryDTO totalPaidInstallments(Integer totalPaidInstallments) {
    this.totalPaidInstallments = totalPaidInstallments;
    return this;
  }

   /**
   * Get totalPaidInstallments
   * @return totalPaidInstallments
  **/
  public Integer getTotalPaidInstallments() {
    return totalPaidInstallments;
  }

  public void setTotalPaidInstallments(Integer totalPaidInstallments) {
    this.totalPaidInstallments = totalPaidInstallments;
  }

  public LoanSummaryDTO percentagePayOff(Double percentagePayOff) {
    this.percentagePayOff = percentagePayOff;
    return this;
  }

   /**
   * Get percentagePayOff
   * @return percentagePayOff
  **/
  public Double getPercentagePayOff() {
    return percentagePayOff;
  }

  public void setPercentagePayOff(Double percentagePayOff) {
    this.percentagePayOff = percentagePayOff;
  }

  public LoanSummaryDTO outstandingAmount(Double outstandingAmount) {
    this.outstandingAmount = outstandingAmount;
    return this;
  }

   /**
   * Get outstandingAmount
   * @return outstandingAmount
  **/
  public Double getOutstandingAmount() {
    return outstandingAmount;
  }

  public void setOutstandingAmount(Double outstandingAmount) {
    this.outstandingAmount = outstandingAmount;
  }

  public LoanSummaryDTO installmentAmount(Double installmentAmount) {
    this.installmentAmount = installmentAmount;
    return this;
  }

   /**
   * Get installmentAmount
   * @return installmentAmount
  **/
  public Double getInstallmentAmount() {
    return installmentAmount;
  }

  public void setInstallmentAmount(Double installmentAmount) {
    this.installmentAmount = installmentAmount;
  }

  public LoanSummaryDTO upcomingInstallmentDate(LocalDate upcomingInstallmentDate) {
    this.upcomingInstallmentDate = upcomingInstallmentDate;
    return this;
  }

   /**
   * Get upcomingInstallmentDate
   * @return upcomingInstallmentDate
  **/
  public LocalDate getUpcomingInstallmentDate() {
    return upcomingInstallmentDate;
  }

  public void setUpcomingInstallmentDate(LocalDate upcomingInstallmentDate) {
    this.upcomingInstallmentDate = upcomingInstallmentDate;
  }

  public LoanSummaryDTO upcomingInstallmentLoanType(String upcomingInstallmentLoanType) {
    this.upcomingInstallmentLoanType = upcomingInstallmentLoanType;
    return this;
  }

   /**
   * Get upcomingInstallmentLoanType
   * @return upcomingInstallmentLoanType
  **/
  public String getUpcomingInstallmentLoanType() {
    return upcomingInstallmentLoanType;
  }

  public void setUpcomingInstallmentLoanType(String upcomingInstallmentLoanType) {
    this.upcomingInstallmentLoanType = upcomingInstallmentLoanType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanSummaryDTO LoanSummaryDTO = (LoanSummaryDTO) o;
    return Objects.equals(this.totalInstallments, LoanSummaryDTO.totalInstallments) &&
        Objects.equals(this.totalPastInstallments, LoanSummaryDTO.totalPastInstallments) &&
        Objects.equals(this.totalPaidInstallments, LoanSummaryDTO.totalPaidInstallments) &&
        Objects.equals(this.percentagePayOff, LoanSummaryDTO.percentagePayOff) &&
        Objects.equals(this.outstandingAmount, LoanSummaryDTO.outstandingAmount) &&
        Objects.equals(this.installmentAmount, LoanSummaryDTO.installmentAmount) &&
        Objects.equals(this.upcomingInstallmentDate, LoanSummaryDTO.upcomingInstallmentDate) &&
        Objects.equals(this.upcomingInstallmentLoanType, LoanSummaryDTO.upcomingInstallmentLoanType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalInstallments, totalPastInstallments, totalPaidInstallments, percentagePayOff, outstandingAmount, installmentAmount, upcomingInstallmentDate, upcomingInstallmentLoanType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanSummaryDTO {\n");
    
    sb.append("    totalInstallments: ").append(toIndentedString(totalInstallments)).append("\n");
    sb.append("    totalPastInstallments: ").append(toIndentedString(totalPastInstallments)).append("\n");
    sb.append("    totalPaidInstallments: ").append(toIndentedString(totalPaidInstallments)).append("\n");
    sb.append("    percentagePayOff: ").append(toIndentedString(percentagePayOff)).append("\n");
    sb.append("    outstandingAmount: ").append(toIndentedString(outstandingAmount)).append("\n");
    sb.append("    installmentAmount: ").append(toIndentedString(installmentAmount)).append("\n");
    sb.append("    upcomingInstallmentDate: ").append(toIndentedString(upcomingInstallmentDate)).append("\n");
    sb.append("    upcomingInstallmentLoanType: ").append(toIndentedString(upcomingInstallmentLoanType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
